### ISSUE TITLE
Add learning resources in README section

### ISSUE THREAD

**Issue by saurabhnative** [codeclassifiers/react30_4_user_feed_app#2]
Add learning resources in README.md section related to `useEffect` hook and how to make API calls in react.js components.
Any links to youtube tutorials, official docs or articles from Medium, Dev.to or Hashnode are preferred.

**Comment by aredshaw** [comment]
I could come up with list if you like. May I take this one?

**Comment by saurabhnative** [comment]
@aredshaw Sure. You have been assigned this issue. Feel free to submit pull request with updated docs.

**Comment by aredshaw** [comment]
Thanks.

**Comment by aredshaw** [comment]
I just created the pull request. I think I found some good resources for learning about useEffect. Let me know if you want any changes.

**Comment by saurabhnative** [comment]
@aredshaw Your PR is merged. Thank you for contributing to this repository.

**Comment by Ousainu** [comment]
@codeclassifiers May I also contribute to this issue?

**Comment by Ousainu** [comment]
@codeclassifiers I have opened a pr for this issue with sections for videos and docs for readability in case there are any more resources you want to add in the future! Take a look and if there are any changes you would like me to make, please let me know.

**Comment by saurabhnative** [comment]
@Ousainu Thank you for your contribution. I have added labels as per official Hacktoberfest guidelines and merged the pull request.
Let me know if there are any issues in Hacktoberfest dashboard.
