### ISSUE TITLE
Build your own variation of scrollable user feed

### ISSUE THREAD

**Issue by saurabhnative** [codeclassifiers/react30_4_user_feed_app#3]
Modify the CSS or the base code to build your own version of user feed.
Submissions by multiple contributors to this issue are allowed.
Steps to contribute:
1. Comment on this issue if you are interested in building your own version
2. Wait for being assigned to the issue and getting solution number
3. Once solution number is assigned, clone the repository and create a folder `solution_[your_assigned_number]` in the repo.
    For example if `solution_3` is assigned to you then you need to create a folder `solution_3` in this repo.
4. If you are a beginner who would only like to modify CSS then copy the code from `solution_1` folder into your assigned folder. If you know react and want to build your own solution then copy the code from `1_starter_code` into your assigned folder.
5. Once finished submit your solution as pull request to this repository. 

Note: No pull request will be accepted until you are added as an assignee to this issue.

**Comment by William-Schutte** [comment]
Hello! I would like to try this challenge.
To clarify, there are classNames used but not defined in the CSS. We would need to define those classes to make the layout work?

**Comment by saurabhnative** [comment]
@William-Schutte Sure you can give this a try. Most of the classes used are from [Bootstrap CSS framework](https://getbootstrap.com/docs/4.5/getting-started/introduction/)
There might not be any need to implement the ones already available from Bootstrap. For any other classes, you can modify and implement them as per the needs of your solution.
Once your solution is implemented you can add your solution in `solution_2` folder while submitting a pull request to this repository.

**Comment by William-Schutte** [comment]
I thought they were Bootstrap classes. I see now it's linked already in the HTML file. 
I'll give it a shot and submit my solution_2 folder when its done. Thanks!

**Comment by saurabhnative** [comment]
@all-contributors please add @William-Schutte  for adding solution_2 to this project
